# Generated by Django 4.2.12 on 2024-05-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_v2', '0002_room_created_at_room_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
