# Generated by Django 4.2.12 on 2024-05-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_v2', '0004_message_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timetaken',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
